#!/bin/sh

serial=/dev/ttyUSB0

if [ "$1" == "-h" ] ; then
    cat 1>&2 <<EOF
FrugalWatchdog helper script.
Parameters:

  timeout <seconds>
  start
  stop
  reset
  status
  clearmem

Running without parameters implies 'start' and 'reset'. The 'status'
command will print the elapsed time and the time of last reset using
the time format of your current locale.

Parameters 'test' and 'repair' are aliased to 'reset' for compatibility
with the watchdog(8) daemon. This script can be dropped in the
/etc/watchdog.d/ directory.
EOF
fi

exec 3<> "$serial" || exit $?
stty 2400 hupcl igncr < "$serial" || exit $?

if [ -z "$1" ] || [ "$1" = "reset" ] || [ "$1" = "start" ] \
   || [ "$1" = "test" ] || [ "$1" = "repair" ] ; then
    printf "reset\r%s\r" "$(date +%s)" >&3
elif [ "$1" = "timeout" ] && [ -n "$2" ] ; then
    printf "timeout\r%s\r" "$2" >&3
elif [ "$1" = "status" ] ; then
    printf "status\r" >&3
    read line <&3
    printf "Elapsed: %s s\n" $line
    read line <&3
    d=$(date -d @"$line")
    printf "Watchdog was last triggered at: %s\n" "$d"
elif [ "$1" = "stop" ] ; then
    printf "stop\r" >&3
elif [ "$1" = "clearmem" ] ; then
    printf "clearmem\r" >&3
fi
